<?php
$title = 'Registrace';
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title);?></h2>
<?php 
$form = $this->form;
$form->setAttribute('action', $this->url(
	'user',
	array(
		'action' => 'register',
	)));

$formLabel = $this->plugin('formLabel');
$form->prepare();

echo $this->form()->openTag($form);?>
<table>
	<tbody>
		<tr>
			<td id="email-label">
			<?php $email = $form->get('email');
			echo $formLabel->openTag() . $email->getOption('label') . $formLabel->closeTag();?>
			</td>
			<td>
			<?php echo $this->formInput($email);
			echo $this->formElementErrors($email);?>
			</td>
		</tr>
		<tr>
			<td id="password-label">
			<?php $password = $form->get('password');
			echo $formLabel->openTag() . $password->getOption('label') . $formLabel->closeTag();?>
			</td>
			<td>
			<?php echo $this->formPassword($password);
			echo $this->formElementErrors($password);?>
			</td>
		</tr>
		<tr>
			<td id="confirmPassword-label">
			<?php $confirmPassword = $form->get('confirmPassword');
			echo $formLabel->openTag() . $confirmPassword->getOption('label') . $formLabel->closeTag();?>
			</td>
			<td>
			<?php echo $this->formPassword($confirmPassword);
			echo $this->formElementErrors($confirmPassword);?>
			</td>
		</tr>
		<tr>
			<td id="captcha-label">
			<?php $captcha = $form->get('captcha');
			echo $formLabel->openTag() . $captcha->getOption('label') . $formLabel->closeTag();?>
			</td>
			<td>
			<?php echo $this->formCaptcha($captcha);
			echo $this->formElementErrors($captcha);?>
			</td>
		</tr>
		<tr>
			<td colspan="2">
			<?php echo $this->formElement($form->get('create'));?>
			</td>
		</tr>
		<?php echo $this->formHidden($form->get('csrf'));?>
	</tbody>
</table>
<?php echo $this->form()->closeTag();