<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->headMeta()->appendHttpEquiv('Content-Type',
										 'text/html;charset=UTF-8');
echo $this->headMeta();?>
<head>
	<?php $this->headTitle(' - Ukázková aplikace - Zend Framework ');
	echo $this->headTitle();?>
	<?php $this->headLink()->appendStylesheet($this->basePath() . '/css/global.css', 'screen, projection'); ?>
	<?php $this->headLink()->appendStylesheet($this->basePath() . '/css/screen.css', 'screen, projection'); ?>
	<?php $this->headLink()->appendStylesheet($this->basePath() . '/css/ie.css', 'screen, projection', 'IE');?>
	<?php $this->headLink()->appendStylesheet($this->basePath() . '/css/print.css', 'print'); ?>
	<?php echo $this->headLink();?>
</head>
<body>
<div class="container">
	<div id="header" class="prepend-top"><div id="logged-in-as" class="push-20 last span-4">
	<?php echo $this->partial('partials/loggedinas.phtml'); ?></div>
		<h1 class="span-19 pull-4 border"><?php echo "Internetové knihkupectví"; ?></h1></div>
	<div id="main-content" class="span-24">
		<?php $children = $this->viewModel()
								->getCurrent()
								->getChildren();
		$actionView = $children[0];
		if(isset($actionView->flashMessages) && count($actionView->flashMessages)) : ?>
		<div class="messages">
			<?php foreach($actionView->flashMessages as $message) :?>
			<p><?php echo $message?></p>
			<?php endforeach; ?>
		</div>
		<?php endif; ?>
		<?php echo $this->content; ?>
	</div>
</div>

</body>
</html>